---
downloads: ~/.ansible-downloads/

configure_dotfiles: true

#Dont need to configure terminal leave default for now
configure_terminal: false

configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - Siri
  - Mail
  - Safari
  - Contacts
  - Calendar
  - Notes
  - Reminders
  - Maps
  - Photos
  - iTunes
  - iBooks
  - 'App Store'
  - TV
  - Podcasts
  - System Preferences

dockitems_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
#  - name: IntelliJ IDEA CE
#    path: "/Applications/IntelliJ IDEA CE.app"
#    pos: 2
#  - name: iTerm
#    path: "/Applications/iTerm.app"
#    pos: 4
#  - name: Slack
#    path: /Applications/Slack.app
#    pos: 5
  - name: WhatsApp
    path: /Applications/WhatsApp.app
    pos: 7
  - name: Telegram
    path: /Applications/Telegram.app
    pos: 8
  - name: Messages
    path: /Applications/Messages.app
    pos: 9
  - name: FaceTime
    path: /Applications/FaceTime.app
    pos: 11

configure_sudoers: true
#sudoers_custom_config: ''
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL



 # Managed via GNU STOW Now

 #dotfiles_repo: git@github.com:f1gjam/dotfiles.git
 #dotfiles_repo_version: main
 #dotfiles_repo_accept_hostkey: yes
 #dotfiles_repo_local_destination: ~/github/dotfiles
 #dotfiles_home: ~/
 #dotfiles_files:
 #  - .bash_profile
 # - .bashrc
 # - .gitconfig
 # - .gitignore
 # - .nanorc
 # - .osx
#  - .ssh

homebrew_installed_packages:
  # - ansible # Installed via Pip.
brew install awscli
  - atac
  - bash
  - bash-completion@2
  - colordiff
  - curl
  - dockutil
  - dos2unix
  - ffmpeg
  - ghostty
  - git
  - git-extras
  - go
  - httpie
  - iperf
  - mongosh
  - mongodb-compass
  - nano
  - nanorc
  - okta-aws-cli
  - python3
  - ruff
  - screen
  - ssh-copy-id
  - starship
  - stow
  - tig
  - tree
  - uv  
  - wget
  - yarn
  - zellij

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - appcleaner
  - cyberduck
  - firefox
  - google-drive
  - google-chrome
  - jetbrains-toolbox
  - microsoft-remote-desktop
  - telegram
  - visual-studio-code
  - vlc
  - whatsapp


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A

pip_packages:
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

