---
- hosts: localhost
  user: kashif
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew
  
  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/extra-packages.yml
    - include: tasks/initial_setup_tasks.yml
    - include: tasks/dock_setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/osx.yml
