---

- name: Set zsh as shell
  shell: defaults write com.apple.Terminal 'Shell' -string '/bin/zsh'
  tags: zsh

- name: Install ohmyzsh
  get_url: 
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh 
    dest: /tmp/zsh-installer.sh
    mode: 0755
  tags: zsh

- name: Execute the zsh-installer.sh
  shell: ./zsh-installer.sh
  args:
    chdir: /tmp
  become: true
  tags: zsh 

- name: Ensure powerline zsh theme repository is cloned locally.
  git:
    repo: "{{ powerline_repo }}"
    dest: "{{ powerline_repo_local_destination }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: no
  tags: zsh

- name: Install Powerline Theme
  shell: ./install_in_omz.sh  
  args:
    chdir: "{{ powerline_repo_local_destination }}"
  tags: zsh

- name: Ensure powerline fonts repository is cloned locally.
  git:
    repo: "{{ fonts_repo }}"
    dest: "{{ fonts_repo_local_destination }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: no
  tags: zsh

- name: Install fonts for powerline theme 
  shell: ./install.sh
  args:
    chdir: "{{ fonts_repo_local_destination }}"
  tags: zsh

